version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
     - '62136:443'
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ConnectionString=Host=db;Database=postgres;Username=postgres;Password=postgres
    depends_on:
    - db

  db:
   image: postgres:15.3-alpine
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - '5436:5432'
   volumes:
     - "./postgres-data:/var/lib/postgresql/data"
     - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  postgres-data:
