CREATE TABLE ROLES (
  ROLE_ID SERIAL NOT NULL,
  ROLE_NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (ROLE_ID)
);

insert into ROLES(ROLE_NAME) values('CUSTOMER');
insert into ROLES(ROLE_NAME) values('COOK');

CREATE TABLE USER_STATUS (
  USER_STATUS_ID SERIAL NOT NULL,
  USER_STATUS_NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (USER_STATUS_ID)
);

insert into USER_STATUS(USER_STATUS_NAME) values('AVAILABLE');
insert into USER_STATUS(USER_STATUS_NAME) values('WORKING');
insert into USER_STATUS(USER_STATUS_NAME) values('INACTIVE');

CREATE TABLE ORDER_STATUS (
  ORDER_STATUS_ID SERIAL NOT NULL,
  ORDER_STATUS_NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (ORDER_STATUS_ID)
);

insert into ORDER_STATUS(ORDER_STATUS_NAME) values('NEW');
insert into ORDER_STATUS(ORDER_STATUS_NAME) values('IN PROGRESS');
insert into ORDER_STATUS(ORDER_STATUS_NAME) values('READY TO PICK');
insert into ORDER_STATUS(ORDER_STATUS_NAME) values('COMPLETED');
insert into ORDER_STATUS(ORDER_STATUS_NAME) values('CANCELLED');

CREATE TABLE ITEM_TYPE (
  ITEM_TYPE_ID SERIAL NOT NULL,
  ITEM_TYPE_NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (ITEM_TYPE_ID)
);

insert into ITEM_TYPE(ITEM_TYPE_NAME) values('PIZZA');
insert into ITEM_TYPE(ITEM_TYPE_NAME) values('SALAD');

CREATE TABLE users
(
    user_id BIGSERIAL NOT NULL,
    user_name character varying(30) NOT NULL,
    password character varying(100),
    email character varying(50) NOT NULL,
    role_id int DEFAULT 1,
    user_status_id int DEFAULT 1,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES roles (role_id) ,
    CONSTRAINT user_status_fk FOREIGN KEY (user_status_id) REFERENCES user_status (user_status_id) 
);

CREATE TABLE ORDERS (
  order_id SERIAL NOT NULL,
  USER_ID BIGINT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  ORDER_STATUS_ID INTEGER DEFAULT 1,
  PRIMARY KEY (order_id),
  CONSTRAINT user_fk FOREIGN KEY (USER_ID) REFERENCES users (USER_ID) ,
  CONSTRAINT order_status_fk FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ORDER_STATUS_ID) 
);

CREATE TABLE MENU (
  ITEM_ID SERIAL NOT NULL,
  ITEM_NAME VARCHAR(100) NOT NULL UNIQUE,
  PRICE FLOAT NOT NULL,
  ITEM_TYPE_ID INTEGER NOT NULL,
  IS_CUSTOM BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (ITEM_ID),
  CONSTRAINT ITEM_TYPE_ID_FK FOREIGN KEY (ITEM_TYPE_ID) REFERENCES ITEM_TYPE (ITEM_TYPE_ID)
);

CREATE TABLE ORDER_DETAILS (
  order_details_id SERIAL NOT NULL,
  order_id INT NOT NULL,
  ITEM_ID INTEGER NOT NULL,
  IS_READY BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (order_details_id),
  CONSTRAINT order_detail_fk FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT item_order_details_fk FOREIGN KEY (ITEM_ID) REFERENCES MENU(ITEM_ID)
 
);

CREATE TABLE CUSTOMIZED_MENU_PRODUCTS (
  PRODUCT_ID INTEGER NOT NULL,
  ITEM_ID INTEGER NOT NULL,
  PRIMARY KEY (PRODUCT_ID, ITEM_ID)
);

CREATE TABLE CUSTOM_PRODUCTS (
  PRODUCT_ID SERIAL NOT NULL,
  PRODUCT_NAME VARCHAR(100) NOT NULL UNIQUE,
  PRICE FLOAT NOT NULL,
  PRODUCT_TYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (PRODUCT_ID),
  FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES ITEM_TYPE (ITEM_TYPE_ID)
);